# 阶段1：构建React项目
FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 阶段2：使用Nginx部署
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html/school
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]